name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/fastapi-simple-board:latest .
          docker push ${{ secrets.DOCKER_USER }}/fastapi-simple-board:latest

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/fastapi-simple-board:latest || true
            docker stop fastapi-simple-board || true
            docker rm fastapi-simple-board || true
            docker run -d -p 8001:8001 --name fastapi-simple-board ${{ secrets.DOCKER_USER }}/fastapi-simple-board:latest